### ISSUE TITLE
[Architecture] Proposal: Extract repository information in an async job

### ISSUE THREAD

**Issue by zergov** [visevol/GihubVisualisation#5]
# Proposal: Extract repository information in an async job
Today, this is how the API serves a user requesting information about a repository:
[![](https://mermaid.ink/img/pako:eNp9kk1Lw0AQhv_KsAdPrS0eF6yIleJBKOgxULbZSbKwH3E_1FD6351km0psMYewmX3emXcmc2Clk8g4C_iR0Ja4VqL2whQW6GmFj6pUrbARnrRCGy_jj9uXHNy7b3Be2Bqh7aRXWqOHG6jVFZHH1gUQAbbdOpOXDAl7YjPq0cp8yE7mqxWV5rB5fodF6YxRMTwkr-9J16T9LYUWXigd8jtLSUG6oTqHCmPZ7ITWu5M8M8MtUZSHDyZK7SzCf2knkhQGGKKDWsSGhpDTQ-WdyaiKzndZSuT819LJCEgRxTT1CdgnpSUI0CpEcBUULEsKdsWJR-M-8aJkZsb5TXrv50MXecIc7pZLmJ9rTcjzTxjZ7Ix2p23gi2YF1PofaWHZjBn0RihJK3foMxWMOIMF43SUWImkh2aOhIoU3VtnS8ajTzhj3qW6YbwSOtBXamlK476eoyj7Tl_zUg-7ffwB_AD7XA?type=png)](https://mermaid.live/edit#pako:eNp9kk1Lw0AQhv_KsAdPrS0eF6yIleJBKOgxULbZSbKwH3E_1FD6351km0psMYewmX3emXcmc2Clk8g4C_iR0Ja4VqL2whQW6GmFj6pUrbARnrRCGy_jj9uXHNy7b3Be2Bqh7aRXWqOHG6jVFZHH1gUQAbbdOpOXDAl7YjPq0cp8yE7mqxWV5rB5fodF6YxRMTwkr-9J16T9LYUWXigd8jtLSUG6oTqHCmPZ7ITWu5M8M8MtUZSHDyZK7SzCf2knkhQGGKKDWsSGhpDTQ-WdyaiKzndZSuT819LJCEgRxTT1CdgnpSUI0CpEcBUULEsKdsWJR-M-8aJkZsb5TXrv50MXecIc7pZLmJ9rTcjzTxjZ7Ix2p23gi2YF1PofaWHZjBn0RihJK3foMxWMOIMF43SUWImkh2aOhIoU3VtnS8ajTzhj3qW6YbwSOtBXamlK476eoyj7Tl_zUg-7ffwB_AD7XA)

The orange section is very expensive. We shouldn't do this work each read requests. We should clone and invoke Git to extract information about the repo only once. The extracted data should be written to a database, and the application should read from this database. 

This is the new flow I propose we do:
Scenario: The user requests information about the `github.com/rails/rails` repository.
[![](https://mermaid.ink/img/pako:eNp9UktvwjAM_itWruOxsVulgSbGgUloaEzapZfQGMjWJsxNBBXiv89pKAN1Ww9V6n4P57MPIrMKRSJK_PJoMnzSck2ySA3ws5XkdKa30jgY5xqNa9cf59N2kXBrS5BlPGhnSWPZU8s28sMuA-61wVVTo3CvzfrZntDRuDsc3rBVAvOXxRv0L3VHnvKHtXYbv-xltuiT1HkZ31GBeUyvKQn8DgT2LF05ioQa2mVO7WjsLzJjQukQuDOqYGUJ_mvgWi-rqQrI7mDHLNAKUnE3uE_FpREnk8DE8Fg8gj6lUucV7IIkBM6ZwZRuzCqBwe0g_mB4IzXOrcGfgVQtwGTvSGYOlHQSVmSLcKc_CKcU3klzCDVBG2jmewWZSfo8dxtGnQq-v6pSARDhqREdUSAVUivexEOopsJtsMBUJHxUuJI-dyGeI0Old3ZRmUwkjjx2BFm_3ohkJfOSv_yW22nW-FxFFa4wi7ter_zxG1pB_no?type=png)](https://mermaid.live/edit#pako:eNp9UktvwjAM_itWruOxsVulgSbGgUloaEzapZfQGMjWJsxNBBXiv89pKAN1Ww9V6n4P57MPIrMKRSJK_PJoMnzSck2ySA3ws5XkdKa30jgY5xqNa9cf59N2kXBrS5BlPGhnSWPZU8s28sMuA-61wVVTo3CvzfrZntDRuDsc3rBVAvOXxRv0L3VHnvKHtXYbv-xltuiT1HkZ31GBeUyvKQn8DgT2LF05ioQa2mVO7WjsLzJjQukQuDOqYGUJ_mvgWi-rqQrI7mDHLNAKUnE3uE_FpREnk8DE8Fg8gj6lUucV7IIkBM6ZwZRuzCqBwe0g_mB4IzXOrcGfgVQtwGTvSGYOlHQSVmSLcKc_CKcU3klzCDVBG2jmewWZSfo8dxtGnQq-v6pSARDhqREdUSAVUivexEOopsJtsMBUJHxUuJI-dyGeI0Old3ZRmUwkjjx2BFm_3ohkJfOSv_yW22nW-FxFFa4wi7ter_zxG1pB_no)

In this model:
1. We first check to see if we have data about the repository
2. If we don't, we create an entry for the `github.com/rails/rails` repository in our database and enqueue a background job to process that repo.
3. we return to the user instantly. 

The background job will clone, extract data from the repo, and write that data into our database. Once its done, it will mark the repo as "ready".

Once that's done, future requests for the `github.com/rails/rails` repository will use this flow:
[![](https://mermaid.ink/img/pako:eNptkVtLAzEQhf_KkEfp2otvAStFi_ggCPq4IGMy2w1skjUXZCn9704TWpWap8k535yEmb1QXpOQItJnJqfoweAuoG0d8BkxJKPMiC7B_WDIpUt98_J0KQYafQSMtTDJB0PxWn9UskY16zX3SnjcvsH8Nzdfrm4qyD5TxZMlCtjiAvV0V4niNaeoieI_jZEGUgmuoAvegvLWmhThq6dApf_daLiF86N_IzUm_MlktX5ewmqxgKbYYiYsBYtG8xz3R7gVqSdLrZBcauowD6kVrTswijn518kpIVPINBPB510vZIdD5FseOfG0hLNK-jia57qpsrDDN8Vej20?type=png)](https://mermaid.live/edit#pako:eNptkVtLAzEQhf_KkEfp2otvAStFi_ggCPq4IGMy2w1skjUXZCn9704TWpWap8k535yEmb1QXpOQItJnJqfoweAuoG0d8BkxJKPMiC7B_WDIpUt98_J0KQYafQSMtTDJB0PxWn9UskY16zX3SnjcvsH8Nzdfrm4qyD5TxZMlCtjiAvV0V4niNaeoieI_jZEGUgmuoAvegvLWmhThq6dApf_daLiF86N_IzUm_MlktX5ewmqxgKbYYiYsBYtG8xz3R7gVqSdLrZBcauowD6kVrTswijn518kpIVPINBPB510vZIdD5FseOfG0hLNK-jia57qpsrDDN8Vej20)

The request can be served to the user without having to invoke Git or clone the repository. 

### References
Reference to some benchmark I did to see how Git performs: https://github.com/zergov/git-benchmarking

**Comment by zergov** [comment]
J'ai aussi faite un figma qui montre un peu les differents flow, on pourra utiliser ca dans les rapports

**Comment by syw1-art** [comment]
Ok yeah, downloading the whole repository everytime we want stats about it is surely slow.
Still confusing as to why it's that slow right now though. Makes no sense to take 10+ min to clone the repo and fetch commit data. Was it because it parses all commit data to json?
Anyways, I like the changes. We should add an expiration date to the cache so it doesn't stay there indefinitely. Maybe 1 day should suffice. It would be nice to also have a way to force refresh the cache for a stat request because there could be very active repositories that have multiple commits in a day.
p.s. data return arrows should be dotted on a sequence diagram :)

**Comment by zergov** [comment]
>Still confusing as to why it's that slow right now though. Makes no sense to take 10+ min to clone the repo and fetch commit data. Was it because it parses all commit data to json?

I profiled the `/commits` endpoint here: https://github.com/zergov/GihubVisualisation/pull/1
The reason is so slow is:
1. cloning the repo takes a while for a large repo
2. accessing the stats of which file changed takes very long because PyDriller asks the Git executable for these stats on each commit. 

If you're dealing with a project with 10_000s of commits, that takes a while. 

> We should add an expiration date to the cache so it doesn't stay there indefinitely. 
Which cache are you talking about? If you're talking about the TinyDB cache (the json we have right now), then yes, we should delete it 🔥. 

If you're talking about the Sqlite databases, these are not cache and we should never delete that.

>It would be nice to also have a way to force refresh the cache for a stat request because there could be very active repositories that have multiple commits in a day.

Yes! I was thinking we could add a refresh button on the frontend to trigger a flow that will:
1. Check to see if the latest commit on github is the same we have in our database.
2. If not, then reindex the repository from the latest commit we have in our database

**Comment by syw1-art** [comment]
I was not talking about the current way of storing things. It can go once we implement this new suggested system.
The reasons I say we put expiration dates on git repo data is twofold:
- If we inspect stats of many git repos, we would be storing them all in the db to my understanding so it would take up much space if we never delete them.
- since we will directly access git data from the db if we find them there, we will miss out on more recent commits that we do not fetch from git. e.g. I request data about a repo today, commits were added to that repo tomorrow, I request the data once again 2 days later -> we don't get the information about commits made tomorrow because we only hit the db.

Correct me if I understood your proposal wrong.

**Comment by zergov** [comment]
>I was not talking about the current way of storing things. It can go once we implement this new suggested system.

Gotcha 👌 

>If we inspect stats of many git repos, we would be storing them all in the db to my understanding so it would take up much space if we never delete them.

The space it takes is reasonable. My local database of a big project like rails is 50mb, and that's for a popular repo that was started 20 years ago. That's very small so I don't think storage is an issue here. Also, storage is the cheapest resource. I will gladly trade storage for speed.

>since we will directly access git data from the db if we find them there, we will miss out on more recent commits that we do not fetch from git. e.g. I request data about a repo today, commits were added to that repo tomorrow, I request the data once again 2 days later -> we don't get the information about commits made tomorrow because we only hit the db. Unless you want us to have to click the refresh button to fetch from git

Very gooood observation 👍 I think we can come up with a strategy that will sync the database whenever  a user asks for stats about a repo. Some solutions:
- If a user asks for stats about `github.com/rails/rails`, and the repo was synced 5 minutes ago, then we serve whatever we have in our database. If the user **knows** its out of sync, then that user can just hit the "refresh" button. 

- If a user asks for stats about `github.com/rails/rails`, and the repo was sync yesterday, then we should just automatically enqueue a re-indexing job for the missing data, and let the user know that we're syncing the repo in the background. The frontend can be smart enough to poll the API to know when the sync is complete. This should be fairly quick because ideally we just have sync the delta between the latest commit in our database, and the latest commit on the repo.

**Comment by zergov** [comment]
>p.s. data return arrows should be dotted on a sequence diagram :)

Thanks @syw1-art, I updated all the sequence diagrams 👍

**Comment by syw1-art** [comment]
Wow ok since it takes that little space then it's fine, basically makes no difference.

Another solution is maybe we could request github for the last commit date and compare it to the latest commit date we have stored in db on every git repo stats request so we know its synced or not?

This process seems good overall, but what about the other members of the team?

**Comment by zergov** [comment]
>Another solution is maybe we could request github for the last commit date and compare it to the latest commit date we have stored in db on every git repo stats request so we know its synced or not?

Yoo I love it 👍

**Comment by zergov** [comment]
Closing since we agreed we're going in that direction.
